apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: app-user
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: orders-events
          patternType: literal
        operations: [Describe, Read, Write]
      - resource:
          type: group
          name: orders-consumer
          patternType: literal
        operations: [Read]
